### ISSUE TITLE
Not clear that a disabled block is in a move state

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [rachel-fenichel/blockly-keyboard-experimentation#397]
Disabled and selected:

<img width="276" alt="Image" src="https://github.com/user-attachments/assets/380a0740-f410-4cea-a4e6-b0479f7150d4" />

Disabled and selected and in move state after pressing "M":

<img width="302" alt="Image" src="https://github.com/user-attachments/assets/3366fde4-f17e-4e2e-aa50-ca11077bccae" />

I can't tell and I think keyboard move mode needs to be clearly indicated somehow. Worth discussing more widely whether it's clear enough for regular blocks too before making a change for this.

**Comment by maribethb** [comment]
One thing we talked about was making the block non-disabled when picked up for a move (for both keyboard and mouse drags?). So we can probably go ahead and implement that in addition to whatever we decide for regular blocks.

**Comment by maribethb** [comment]
https://github.com/user-attachments/assets/6d4c8987-a071-4fc3-9d10-9e85c8eedc86

OK, you can do this with a pretty sweet css-only solution like so:

```css
      .zelos-renderer.zelosderived-theme .blocklyBlockDragSurface .blocklyDisabledPattern > .blocklyOutlinePath {
        fill: attr(fill type(<color>));
        fill-opacity: 0.8;
      }

      .blocklyBlockDragSurface .blocklyDisabledPattern > .blocklyPath {
        fill: attr(fill type(<color>));
        fill-opacity: 0.8;
      }
```

However using `attr` like this is experimental and only works in chrome haha. The reason you have to use `attr` is because for non-disabled blocks, we set the fill value through the "fill" attribute in the svg element. then `blocklyDisabledPattern` sets the `fill` value in css. Once the value is set in css, I don't know of any other way to say "no, don't use the value from css, use the value from the attribute" other than the attribute value. So the options are:

- In core blockly, set the `fill` value with css instead of in the attributes so you can more easily manipulate it (probably a breaking change to mess with people's css, but we are already doing some of those in v12)
- Add an event listener that removes the `blocklyDisabledPattern` class when the drag starts and adds it back when it's done. However, we need to be careful because we made it possible for folks to not use the `blocklyDisabledPattern` class (code.org doesn't use it) so we can't just add it back willy nilly.
- Add an event listener that actually un-disables the blocks when the drag starts and re-disables them with their original disabled reasons when the drag ends.

I have also done the last option and it works fine, but it feels like a lot of overkill for something that could theoretically be done in css :/ but that's what I'll put up a PR for unless someone knows more about css than I do and has a solution to this
